repo_url: https://github.com/hstxmgzY/hstxmgzY.github.io
site_name: hstxmgzYYYYYY

nav:
  - Home: "index.html"
  - "about.md"
  - IELTS:
      - Writing:
         - 说明: "ielts/writing/说明.md"
         - Develop Your Idea: "ielts/writing/develop_your_idea.md"
         - 比较利弊: "ielts/writing/Advantages_and_Disadvantage.md"
         - Discuss Both Views: "ielts/writing/Discuss_both_views.md"
         - 同不同意: "ielts/writing/同不同意.md"
         - Report型: "ielts/writing/Causes_and_solution.md"
         - 小作文语料: "ielts/writing/小作文语料.md"
         - 小作文数据图: "ielts/writing/数据图.md"
         - 小作文地图&流程图: "ielts/writing/流程图&地图.md"
  - 刷题小记:
      - 数据结构:
         - 链表: "JF/datastructure/linklist.md"
         - 图: "JF/datastructure/graph.md"
      - 淑芬:
         - OVERALL: "JF/淑芬/OVERALL.md"
      - 机器学习:
         - 参考（必看！！）: "JF/机器学习/info.md"
         - 绪论: "JF/机器学习/Chp0.md"
         - 模型评估与选择: "JF/机器学习/Chp2.md"
         - 线性模型: "JF/机器学习/Chp3.md"
         - 决策树: "JF/机器学习/Chp4.md"
         - 神经网络: "JF/机器学习/Chp5.md"
      - SQL:
         - "JF/sql/SQL概述.md"
         - "JF/sql/数据定义.md"
         - "JF/sql/数据更新.md"
         - "JF/sql/数据查询.md"
      - "概率论与数理统计":
         - "JF/概率论与数理统计/概率论.md"
         - 统计:
           - "JF/概率论与数理统计/统计/第一章 数据的整理和描述.md"
           - "JF/概率论与数理统计/统计/第二章 抽样推断与抽样分布.md"
      - MySQL:
         - "JF/mysql/配置&下载.md"
      - 归档:
         - "202404":
           - "JF/归档/202404/20240423.md"
           - "JF/归档/202404/20240424.md"
         - "202405":
           - "JF/归档/202405/202405.md"
  - Misc:
      - problems: "Misc/hghgh1.md"
      - Git 修改提交的邮箱或用户名: "Misc/chage_commitinfo.md"
  - 大学学习:
      - 备注: "review/index.md"
      - 大三下:
         - 云计算技术:
           - "review/Grade3_2/cloudcp/1.md"
           - "review/Grade3_2/cloudcp/Cloud_Computing.md"
         - 编译原理: "review/Grade3_2/lex/byyl.md"
         - 信息安全技术:
           - 复习: "review/Grade3_2/InfoSec/复习.md"
           - 考试: "review/Grade3_2/InfoSec/test.md"

theme:
  name: material
  custom_dir: overrides/
  language: en
  favicon: WebIcon.svg
  palette:
    primary: white
    accent: red
    scheme: preference
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.path
    - navigation.tabs
    - search.suggest
    - search.share
    - content.code.select
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - search.highlight
  font:
    text: Noto Sans
    code: Source Code Pro
  icon:
    repo: repo_icon
    logo: WebIcon


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

copyright: "Copyright &copy Ywx"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hstxmgzY/hstxmgzY.github.io
    - icon: fontawesome/solid/paper-plane
      link: mailto:gooeyerwz@gmail.com
